# -----------------------------------------------------------------------------
# Tmux config managed by chezmoi. Requires tmux >= 2.3.
# -----------------------------------------------------------------------------

set -g prefix C-x

set -g base-index         0
set -g display-panes-time 10000
set -g mouse              on
set -g pane-base-index    1
set -g renumber-windows   on

bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind C-x send-prefix
bind | split-window -h
bind - split-window -v

setenv -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins'

set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tpm'

set -g @resurrect-dir '~/.tmux/resurrect'

set -g status-right '#{prefix_highlight} #H | %a %Y-%m-%d %H:%M'
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_copy_mode_attr 'fg=white,bg=blue'
set -g @colors-solarized 'dark'

run '~/.tmux/plugins/tpm/tpm'
